name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The persons to greet'
        type: string
        required: true
        default: Ida and Mathias
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hellooo"
